// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoporteAurora.Datos;

#nullable disable

namespace Tarea_6_SI1.Migrations
{
    [DbContext(typeof(SoporteContext))]
    [Migration("20260921031219_m5")]
    partial class m5
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoporteAurora.Models.ActivoTecnologico", b =>
                {
                    b.Property<int>("Id_Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Activo"));

                    b.Property<string>("Codigo_Inventario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha_Compra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Fecha_Vencimiento_Garantia")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Area")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Responsable")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Sucursal")
                        .HasColumnType("integer");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero_Serie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Activo");

                    b.ToTable("ActivosTecnologicos");
                });

            modelBuilder.Entity("SoporteAurora.Models.Diagnostico", b =>
                {
                    b.Property<int>("Id_Diagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Diagnostico"));

                    b.Property<string>("Causa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Encargado")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Ticket")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_Ticket")
                        .HasColumnType("integer");

                    b.HasKey("Id_Diagnostico");

                    b.HasIndex("Id_Ticket");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("SoporteAurora.Models.Ticket", b =>
                {
                    b.Property<int>("Id_Ticket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Ticket"));

                    b.Property<string>("CI_Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Area")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Encargado")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Sucursal")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("integer");

                    b.Property<string>("Impacto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo_Problema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Urgencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Ticket");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("SoporteAurora.Models.Ticket_activo", b =>
                {
                    b.Property<int>("id_Ticket")
                        .HasColumnType("integer");

                    b.Property<int>("id_activo")
                        .HasColumnType("integer");

                    b.HasKey("id_Ticket", "id_activo");

                    b.HasIndex("id_activo");

                    b.ToTable("Ticket_activos");
                });

            modelBuilder.Entity("SoporteAurora.Models.Diagnostico", b =>
                {
                    b.HasOne("SoporteAurora.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("Id_Ticket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SoporteAurora.Models.Ticket_activo", b =>
                {
                    b.HasOne("SoporteAurora.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("id_Ticket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoporteAurora.Models.ActivoTecnologico", "Activo")
                        .WithMany()
                        .HasForeignKey("id_activo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
