// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoporteAurora.Datos;

#nullable disable

namespace Tarea_6_SI1.Migrations
{
    [DbContext(typeof(SoporteContext))]
    [Migration("20260928001513_m12")]
    partial class m12
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoporteAurora.Models.ActivoTecnologico", b =>
                {
                    b.Property<int>("Id_Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Activo"));

                    b.Property<string>("Codigo_Inventario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateOnly>("Fecha_Compra")
                        .HasColumnType("date");

                    b.Property<DateOnly>("Fecha_Vencimiento_Garantia")
                        .HasColumnType("date");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Numero_Serie")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_tipo_activo")
                        .HasColumnType("integer");

                    b.HasKey("Id_Activo");

                    b.HasIndex("id_tipo_activo");

                    b.ToTable("ActivosTecnologicos");
                });

            modelBuilder.Entity("SoporteAurora.Models.Diagnostico", b =>
                {
                    b.Property<int>("Id_Diagnostico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Diagnostico"));

                    b.Property<string>("Causa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Encargado")
                        .HasColumnType("integer");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_Ticket")
                        .HasColumnType("integer");

                    b.HasKey("Id_Diagnostico");

                    b.HasIndex("id_Ticket");

                    b.ToTable("Diagnosticos");
                });

            modelBuilder.Entity("SoporteAurora.Models.Evidencia", b =>
                {
                    b.Property<int>("Id_Evidencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Evidencia"));

                    b.Property<string>("Archivo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Responsable")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_Ticket")
                        .HasColumnType("integer");

                    b.HasKey("Id_Evidencia");

                    b.HasIndex("id_Ticket");

                    b.ToTable("Evidencias");
                });

            modelBuilder.Entity("SoporteAurora.Models.Mantenimiento", b =>
                {
                    b.Property<int>("Id_Mantenimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Mantenimiento"));

                    b.Property<string>("Codigo_Responsable")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Costo")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("id_Activo")
                        .HasColumnType("integer");

                    b.Property<int>("id_Ticket")
                        .HasColumnType("integer");

                    b.HasKey("Id_Mantenimiento");

                    b.HasIndex("id_Activo");

                    b.HasIndex("id_Ticket");

                    b.ToTable("Mantenimientos");
                });

            modelBuilder.Entity("SoporteAurora.Models.Mantenimiento_Repuesto", b =>
                {
                    b.Property<int>("id_Mantenimiento")
                        .HasColumnType("integer");

                    b.Property<int>("id_Repuesto")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.HasKey("id_Mantenimiento", "id_Repuesto");

                    b.HasIndex("id_Repuesto");

                    b.ToTable("Mantenimiento_repuestos");
                });

            modelBuilder.Entity("SoporteAurora.Models.Repuesto", b =>
                {
                    b.Property<int>("Id_Repuesto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Repuesto"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Costo")
                        .HasColumnType("numeric");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.HasKey("Id_Repuesto");

                    b.ToTable("Repuestos");
                });

            modelBuilder.Entity("SoporteAurora.Models.Ticket", b =>
                {
                    b.Property<int>("Id_Ticket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Ticket"));

                    b.Property<string>("CI_Encargado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CI_Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Impacto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo_Problema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Urgencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Ticket");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("SoporteAurora.Models.TicketRepuesto", b =>
                {
                    b.Property<int>("id_Ticket")
                        .HasColumnType("integer");

                    b.Property<int>("id_Repuesto")
                        .HasColumnType("integer");

                    b.Property<int>("Cantidad")
                        .HasColumnType("integer");

                    b.HasKey("id_Ticket", "id_Repuesto");

                    b.HasIndex("id_Repuesto");

                    b.ToTable("Ticket_repuestos");
                });

            modelBuilder.Entity("SoporteAurora.Models.Ticket_activo", b =>
                {
                    b.Property<int>("id_Ticket")
                        .HasColumnType("integer");

                    b.Property<int>("id_activo")
                        .HasColumnType("integer");

                    b.HasKey("id_Ticket", "id_activo");

                    b.HasIndex("id_activo");

                    b.ToTable("Ticket_activos");
                });

            modelBuilder.Entity("SoporteAurora.Models.Tipo_activo", b =>
                {
                    b.Property<int>("Id_tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_tipo"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_tipo");

                    b.ToTable("Tipos_activos");
                });

            modelBuilder.Entity("SoporteAurora.Models.ActivoTecnologico", b =>
                {
                    b.HasOne("SoporteAurora.Models.Tipo_activo", "tipo_Activo")
                        .WithMany()
                        .HasForeignKey("id_tipo_activo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("tipo_Activo");
                });

            modelBuilder.Entity("SoporteAurora.Models.Diagnostico", b =>
                {
                    b.HasOne("SoporteAurora.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("id_Ticket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SoporteAurora.Models.Evidencia", b =>
                {
                    b.HasOne("SoporteAurora.Models.Ticket", "ticket")
                        .WithMany()
                        .HasForeignKey("id_Ticket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ticket");
                });

            modelBuilder.Entity("SoporteAurora.Models.Mantenimiento", b =>
                {
                    b.HasOne("SoporteAurora.Models.ActivoTecnologico", "activo")
                        .WithMany()
                        .HasForeignKey("id_Activo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoporteAurora.Models.Ticket", "ticket")
                        .WithMany()
                        .HasForeignKey("id_Ticket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("activo");

                    b.Navigation("ticket");
                });

            modelBuilder.Entity("SoporteAurora.Models.Mantenimiento_Repuesto", b =>
                {
                    b.HasOne("SoporteAurora.Models.Mantenimiento", "mantenimiento")
                        .WithMany()
                        .HasForeignKey("id_Mantenimiento")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoporteAurora.Models.Repuesto", "repuesto")
                        .WithMany()
                        .HasForeignKey("id_Repuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("mantenimiento");

                    b.Navigation("repuesto");
                });

            modelBuilder.Entity("SoporteAurora.Models.TicketRepuesto", b =>
                {
                    b.HasOne("SoporteAurora.Models.Repuesto", "repuesto")
                        .WithMany()
                        .HasForeignKey("id_Repuesto")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoporteAurora.Models.Ticket", "ticket")
                        .WithMany()
                        .HasForeignKey("id_Ticket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("repuesto");

                    b.Navigation("ticket");
                });

            modelBuilder.Entity("SoporteAurora.Models.Ticket_activo", b =>
                {
                    b.HasOne("SoporteAurora.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("id_Ticket")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SoporteAurora.Models.ActivoTecnologico", "Activo")
                        .WithMany()
                        .HasForeignKey("id_activo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activo");

                    b.Navigation("Ticket");
                });
#pragma warning restore 612, 618
        }
    }
}
