// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SoporteAurora.Datos;

#nullable disable

namespace Tarea_6_SI1.Migrations
{
    [DbContext(typeof(SoporteContext))]
    [Migration("20260920183851_m1")]
    partial class m1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoporteAurora.Models.Ticket", b =>
                {
                    b.Property<int>("Id_Ticket")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Ticket"));

                    b.Property<string>("CI_Usuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Id_Area")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Encargado")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Sucursal")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("integer");

                    b.Property<string>("Impacto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo_Problema")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Urgencia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_Ticket");

                    b.ToTable("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
